### ISSUE TITLE
Am I doing something dumb?

### ISSUE THREAD

**Issue by andrew-buchanan** [miguel-ambrona/deadpos#36]
N1R5/1k6/8/8/8/8/6p1/6Bq b >>= r >>= r >>= h=1
>>> N1R5/1k6/8/8/8/8/6p1/6Bq b >>= r >>= r >>= h=1
Traceback (most recent call last):
  File "/home/dawson/deadpos/src/deadpos.py", line 411, in <module>
    main()
  File "/home/dawson/deadpos/src/deadpos.py", line 403, in main
    positions, n = process_cmd(positions, cmd)
  File "/home/dawson/deadpos/src/deadpos.py", line 337, in process_cmd
    positions = bind(positions, backwards)
  File "/home/dawson/deadpos/src/deadpos.py", line 324, in bind
    return [b for el in elements for b in function(el)]
  File "/home/dawson/deadpos/src/deadpos.py", line 324, in <listcomp>
    return [b for el in elements for b in function(el)]
  File "/home/dawson/deadpos/src/deadpos.py", line 258, in backwards
    for (retracted_fen, retraction) in retract(fen):
  File "/home/dawson/deadpos/src/solver.py", line 39, in retract
    retracted_fen, retraction = output.split('retraction')
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by miguel-ambrona** [comment]
There is no white king in that position.

I'll add a sanity check on input FENs.
